title:               Árni Sturluson
url:                 "https://Surluson.github.io"
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Árni Sturluson 
  url:               Surluson.github.io
  email:             arnisturlu@gmail.com

markdown: kramdown
kramdown:  
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: 1
  show_warnings: false
  enable_coderay: false


plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist